// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Provider from "./provider";
// import AppBar from "./components/appbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Provider>
//           <AppBar/>
// {children}
//         </Provider>
        
//       </body>
//     </html>
//   );
// }
import { ReactNode } from "react";
import Link from "next/link";
import { getServerSession } from "next-auth";
// import { authOptions } from "../lib/auth"; // your nextauth config
import "./globals.css";

export const metadata = {
  title: "Real world Prediction",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="bg-gray-900 text-gray-100 min-h-screen font-sans">
        <header className="bg-gray-800 p-4 flex justify-between items-center shadow-md">
          <Link href="/" className="text-2xl font-bold text-purple-400">
            Predix
          </Link>
          <nav className="flex gap-4 items-center">
            <Link href="/markets" className="hover:text-purple-300 transition">
              Markets
            </Link>
            {session ? (
              <span className="px-3 py-1 bg-gray-700 rounded">{session.user?.name}</span>
            ) : (
              <Link
                href="/api/auth/signin"
                className="px-3 py-1 bg-purple-600 rounded hover:bg-purple-500 transition"
              >
                Sign In
              </Link>
            )}
          </nav>
        </header>

        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
